vich_uploader:
    db_driver: orm

    mappings:
        fichier_article:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles' 

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        image_slider:
            uri_prefix: /images/bg
            upload_destination: '%kernel.project_dir%/public/images/bg'

        profil_user:
            uri_prefix: /images/profil
            upload_destination: '%kernel.project_dir%/public/images/profil' 
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        projet_files:
            uri_prefix:         '/uploads/projets'
            upload_destination: '%kernel.project_dir%/public/uploads/projets'
            namer:              Vich\UploaderBundle\Naming\UniqidNamer